[package]
name = "godot-rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { version = "0.4.2", features = ["experimental-threads"]}
viska-sat = { path = "../viska-sat" }

